cv/urls.py
from django.conf.urls import patterns, url

from cv import views

urlpatterns = patterns('',
    # Example: /employee/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # Example: /employee/1/
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    # Example: /employee/1/generate_form
    url(r'^(?P<pk>\d+)/update$', views.UpdateView.as_view(), name='update'),
    # Example: /employee/1/generate_form
    url(r'^(?P<pk>\d+)/generate_form$', views.DetailView.as_view(), name='generate_form'),
)

cvgenerator/urls.py
from django.conf.urls import patterns, include, url, static
from django.conf import settings

from cvgenerator import views

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cvgenerator.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # Index
    url(r'^$', views.IndexView.as_view(), name="index"),


    # CV namespace
    #url(r'^cv/', include('cv.urls', namespace="cv")),

    # Employee namespace
    url(r'^employee/', include('cv.urls', namespace="employee")),

    # Generator namespace
    url(r'^generator/', include('generator.urls', namespace="generator")),

    # Admin
    url(r'^admin/', include(admin.site.urls)),

    #Media
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT})
)

generator/urls.py
from django.conf.urls import patterns, url

from generator import views

urlpatterns = patterns('',
    # Example: /generator/
    url(r'^$', views.GeneratorIndexView.as_view(), name='index'),
    # Example: /generator/create/
    url(r'^create/$', views.GeneratorCreateView.as_view(), name='create'),
    # Example: /generator/create/1
    url(r'^create/(?P<employee>\d+)/$', views.GeneratorCreateView.as_view(), name='create'),
    # Example: /generator/1
    url(r'^(?P<pk>\d+)/$', views.GeneratorDetailView.as_view(), name='detail'),
)

cvgenerator/views.py
from django.views import generic

from generator.services import get_latest_generated_cv_by_user

class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'latest_cv_by_employee'

    def get_queryset(self):
        return get_latest_generated_cv_by_user()

cvgenerator/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load url from future %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>CONCETO CV GENERATOR</title>
    <meta name="description" content="CV generator">
    <meta name="author" content="Florian Wallburg">
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen" />
	<link href="{% static 'css/styles.css' %}" rel="stylesheet" media="screen" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.1/jquery.min.js"></script>

    {% block extra_head %}{% endblock %}
</head>

<body>

	<div class="container">
		<div class="page-header">
  			<img src="{% static 'img/conceto_logo.jpg' %}"/>
		</div>
		<nav class="navbar navbar-default" role="navigation">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">cvgenerator</a>
			</div>
			<ul class="nav navbar-nav">
				<li><a href="{% url 'generator:index' %}">Generator</a></li>
			</ul>
			<ul class="nav navbar-nav">
				<li><a href="{% url 'employee:index' %}">Employees</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'admin:index' %}">Admin</a></li>
					</ul>
				</li>
			</ul>
		</nav>

	    {% block content %}Empty page{% endblock %}

	    <p><hr></p>

	    <footer class="row">
	        <div class="col-md-6">
	            <p>This is cvgen</p>
	        </div>
	        <div class="col-md-6" style="text-align:right;">
	                &copy; <a href="#">Florian Wallburg</a> 2013 | <a href="#">license</a>
	        </div>
	    </footer>

	</div> <!-- container -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

cvgenerator/templates/index.html
{% extends "base.html" %}

{% block content %}

<ol class="breadcrumb">
    <li><a href="/">Home</a></li>
</ol>

<div class="jumbotron">
	<h1>Use cases</h1>
	<p>Here are the common use cases to use this piece of software.</p>
	<p><a href="{% url 'generator:create' %}" class="btn btn-primary btn-lg" role="button">Generate CV</a>&nbsp;<a href="{% url 'generator:create' %}" class="btn btn-primary btn-lg" role="button">Generate CV</a>&nbsp;<a href="{% url 'generator:create' %}" class="btn btn-primary btn-lg" role="button">Generate CV</a>&nbsp;<a href="{% url 'generator:create' %}" class="btn btn-primary btn-lg" role="button">Generate CV</a>&nbsp;<a href="{% url 'generator:create' %}" class="btn btn-primary btn-lg" role="button">Generate CV</a>&nbsp;<a href="{% url 'generator:create' %}" class="btn btn-primary btn-lg" role="button">Generate CV</a>&nbsp;<a href="{% url 'generator:create' %}" class="btn btn-primary btn-lg" role="button">Generate CV</a></p>
</div>

<h3>Latest generated CVs</h3>

{% if latest_cv_by_employee %}
<table class="table table-striped">
   	<thead>
   		<tr>
   			<th>#</th>
   			<th>Employee</th>
   			<th>Template</th>
   			<th>Date</th>
   			<th>Status</th>
        <th>Tex</th>
   			<th>Media</th>
   		</tr>
   	<tbody>
        {% for generator in latest_cv_by_employee %}
   		<tr>
   			<td>{{ generator.id }}</td>
   			<td>{{ generator.employee }}</td>
   			<td>{{ generator.template }}</td>
   			<td>{{ generator.creation_date }}</td>
   			{% if generator.status %}
   			<td>
   			{% if generator.status == 'Q' %}
   			<button type="button" class="btn btn-warning btn-xs">Queued</button>
   			{% elif generator.status == 'F' %}
   			<button type="button" class="btn btn-success btn-xs">Created</button>
   			{% endif %}
   			{% endif %}
   			</td>
        {% if generator.tex_file %}
        <td><a href="{{ generator.tex_file.url }}"><span class="glyphicon glyphicon-download"></span></a></td>
        {% else %}
        <td><span class="glyphicon glyphicon-ban-circle"></span></a></td>
        {% endif %}
        {% if generator.pdf_file %}
   			<td><a href="{{ generator.pdf_file.url }}"><span class="glyphicon glyphicon-download"></span></a></td>
        {% else %}
        <td><span class="glyphicon glyphicon-ban-circle"></span></a></td>
        {% endif %}
  		</tr>
        {% endfor %}
   	</tbody>
</table>
{% else %}
<div class="alert alert-danger">Yet, no CVs were generated.</div>
{% endif %}

{% endblock %}