cv/urls.py
from django.conf.urls import patterns, url

from cv import views

urlpatterns = patterns('',
    # Example: /employee/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # Example: /employee/1/
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    # Example: /employee/1/generate_form
    url(r'^(?P<pk>\d+)/update$', views.UpdateView.as_view(), name='update'),
    # Example: /employee/1/generate_form
    url(r'^(?P<pk>\d+)/generate_form$', views.DetailView.as_view(), name='generate_form'),
)

cvgenerator/urls.py
from django.conf.urls import patterns, include, url, static
from django.conf import settings

from cvgenerator import views

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cvgenerator.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # Index
    url(r'^$', views.IndexView.as_view(), name="index"),


    # CV namespace
    #url(r'^cv/', include('cv.urls', namespace="cv")),

    # Employee namespace
    url(r'^employee/', include('cv.urls', namespace="employee")),

    # Generator namespace
    url(r'^generator/', include('generator.urls', namespace="generator")),

    # Admin
    url(r'^admin/', include(admin.site.urls)),

    #Media
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT})
)

generator/urls.py
from django.conf.urls import patterns, url

from generator import views

urlpatterns = patterns('',
    # Example: /generator/
    url(r'^$', views.GeneratorIndexView.as_view(), name='index'),
    # Example: /generator/create/
    url(r'^create/$', views.GeneratorCreateView.as_view(), name='create'),
    # Example: /generator/create/1
    url(r'^create/(?P<employee>\d+)/$', views.GeneratorCreateView.as_view(), name='create'),
    # Example: /generator/1
    url(r'^(?P<pk>\d+)/$', views.GeneratorDetailView.as_view(), name='detail'),
)

cv/models.py
# -*- coding: utf-8 -*-
# print test.decode('utf-8')

from django.db import models
from django_countries import CountryField

class Customer(models.Model):
    # Fields
    name = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    country = CountryField(default='DE')
    industry = models.CharField(max_length=100)
    anonymous = models.CharField(max_length=100)

    # Functions
    def count_projects(self):
        return self.project_set.count()
    count_projects.admin_order_field = 'count_projects'
    count_projects.short_description = '# of projects'

    # Self
    def __unicode__(self):
        return "%s" % (self.name)

class Employee(models.Model):
    # Fields
    title = models.CharField(max_length=50, blank=True, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=100)
    place_of_birth = models.CharField(max_length=50)
    year_of_birth = models.IntegerField()
    country_of_birth = CountryField(default='DE')

    LEDIG = 'L'
    VERHEIRATET = 'V'
    FAMILIENSTAND_AUSWAHL = (
        (LEDIG, 'Ledig'),
        (VERHEIRATET, 'Verheiratet'),
    )
    family_status = models.CharField(max_length=1,
        choices=FAMILIENSTAND_AUSWAHL,
        default=LEDIG)

    CONSULTANT = 'CO'
    MANAGING_DIRECTOR = 'MD'
    PROJECT_MANAGER = 'PM'
    SENIOR_CONSULTANT = 'SC'
    POSITION_AUSWAHL = (
       (CONSULTANT, 'Consultant'),
       (MANAGING_DIRECTOR, 'Geschäftsführer'),
       (PROJECT_MANAGER, 'Projektleiter'),
       (SENIOR_CONSULTANT, 'Senior Consultant'),
    )
    position = models.CharField(max_length=2,
        choices=POSITION_AUSWAHL,
        default=CONSULTANT)

    citizenship = models.CharField(max_length=100)
    short_description = models.CharField(max_length=5000)

    creation_date = models.DateTimeField(auto_now_add = True)
    last_change = models.DateTimeField(auto_now = True)

    #Functions
    def count_skills(self):
        return self.skill_set.count()
    count_skills.admin_order_field = 'count_skills'
    count_skills.short_description = '# of skills'

    def count_projects(self):
        return self.project_set.count()
    count_projects.admin_order_field = 'count_projects'
    count_projects.short_description = '# of projects'

    # Self
    def __unicode__(self):
        return "%s %s" % (self.first_name, self.last_name)

class Skill(models.Model):
    # Fields
    APPLICATION_SERVER = 'AS'
    CERTIFICAT = 'C'
    COMMUNICATION_PROTOCOL = 'CP'
    MIDDLEWARE = 'M'
    MESSAGE_FORMAT = 'MF'
    MISC = 'MI'
    MESSAGE_STANDARD = 'MS'
    PROGRAMMING_LANGUAGE = 'PL'
    SAP_MODULE = 'SM'
    SAP_TECHNOLOGY = 'ST'
    KIND_OF_SKILL_AUSWAHL = (
       (APPLICATION_SERVER, 'Applikationsserver'),
       (CERTIFICAT, 'Zertifikat'),
       (COMMUNICATION_PROTOCOL, 'Kommunikationsprotokoll'),
       (MIDDLEWARE, 'Middleware'),
       (MESSAGE_FORMAT, 'Nachrichtenformat'),
       (MESSAGE_STANDARD, 'Nachrichtenstandard'),
       (MISC, 'Andere'),
       (PROGRAMMING_LANGUAGE, 'Programmiersprache'),
       (SAP_MODULE, 'SAP-Modul'),
       (SAP_TECHNOLOGY, 'SAP-Technologie'),
    )
    kind_of_skill = models.CharField(max_length=2,
        choices=KIND_OF_SKILL_AUSWAHL,
        default=APPLICATION_SERVER)

    BASIC = 'B'
    ADVANCED = 'A'
    EXPRERT = 'E'
    LEVEL_AUSWAHL = (
        (BASIC, 'Grundkenntnisse'),
        (ADVANCED, 'Forgeschrittenes Wissen'),
        (EXPRERT, 'Expertenwissen'),
    )
    level = models.CharField(max_length=1,
        choices=LEVEL_AUSWAHL,
        default=BASIC,
        help_text="Kenntnisstand ist bei Zertifikaten ohne Belang!")
    
    skill = models.CharField(max_length=200)

    # Foreign key
    employee = models.ForeignKey(Employee, blank=True, null=True)

class Project(models.Model):
    name = models.CharField(max_length=1000)
    city = models.CharField(max_length=100)
    country_iso_code = CountryField(default='DE')
    position = models.CharField(max_length=100)
    work_start = models.DateField()
    work_end = models.DateField()
    project_start = models.DateField(blank=True, null=True)
    project_end = models.DateField(blank=True, null=True)
    description = models.CharField(max_length=10000,
        blank=True,
        null=True,
        help_text="Bitte Beschreibung allgemein halten da diese auch für anonymisierte Lebensläufe verwendet werden!")

    # Foreign key
    customer = models.ForeignKey(Customer, blank=True, null=True)

    # Foreign key
    employee = models.ForeignKey(Employee, blank=True, null=True)

    # Functions
    def project_duration_in_months(self):
        return self.project_end.month-self.project_start.month
    project_duration_in_months.admin_order_field = 'project_duration_in_months'
    project_duration_in_months.short_description = 'Project duration in months'

    def count_tasks(self):
        return self.task_set.count()
    count_tasks.admin_order_field = 'count_tasks'
    count_tasks.short_description = '# of tasks'

class Task(models.Model):
    description = models.CharField(max_length=600)

    # Foreign key
    project = models.ForeignKey(Project)

class Training(models.Model):
    description = models.CharField(max_length=5000)

    # Foreign key
    employee = models.ForeignKey(Employee, blank=True, null=True)

class Education(models.Model):
    institute = models.CharField(max_length=200)
    branch_of_study = models.CharField(max_length=200)
    study_start = models.DateField()
    study_end = models.DateField()
    degree = models.CharField(max_length=200)
    degree_short = models.CharField(max_length=50, blank=True, null=True)
    thesis_topic = models.CharField(max_length=200, blank=True, null=True)

    # Foreign key
    employee = models.ForeignKey(Employee, blank=True, null=True)

class Spoken_Language(models.Model):
    # Fields
    language = models.CharField(max_length=50)

    GRUNDKENTISSE = 'GK'
    MUTTERSPRACHE = 'MS'
    VERHANDLUNGSSICHER = 'VS'
    KOENNEN_AUSWAHL = (
        (GRUNDKENTISSE, 'Grundkenntnisse'),
        (MUTTERSPRACHE, 'Muttersprache'),
        (VERHANDLUNGSSICHER, 'Verhandlungssicher'),
        )
    skill = models.CharField(max_length=2,
        choices=KOENNEN_AUSWAHL,
        default=MUTTERSPRACHE
        )

    # Foreign key
    employee = models.ForeignKey(Employee, blank=True, null=True)

cv/views.py
#from django.shortcuts import render, get_object_or_404
from django.views import generic

from cv.models import Employee

class IndexView(generic.ListView):
    template_name = 'employee/index.html'
    context_object_name = 'employee_list'

    def get_queryset(self):
        return Employee.objects.order_by('-last_change')[:25]

class DetailView(generic.DetailView):
    model = Employee
    template_name = 'employee/detail.html'

class Generate_FormView(generic.DetailView):
    model = Employee
    template_name = 'employee/generate_form.html'

class UpdateView(generic.UpdateView):
    model = Employee
    fields = ['first_name']
    template_name = 'employee/employee_update_form.html'
    #template_name_suffix = '_update_form'

generator/views.py
from django.views import generic

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from generator.models import Generator
from generator.forms import GeneratorForm

class GeneratorIndexView(generic.ListView):
    template_name = 'generator/index.html'
    context_object_name = 'generator_list'

    def get_queryset(self):
        return Generator.objects.order_by('-creation_date')[:25]

class GeneratorCreateView(generic.CreateView):
    form_class = GeneratorForm
    model = Generator
    fields = ['employee', 'template']
    template_name = 'generator/generator_create_form.html'

    def form_valid(self, form):
        #form.generate_cv()
        form.instance.created_by = self.request.user
        return super(GeneratorCreateView, self).form_valid(form)

    #@method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(GeneratorCreateView, self).dispatch(*args, **kwargs)

class GeneratorDetailView(generic.DetailView):
    model = Generator
    template_name = 'generator/detail.html'

    ''' Aendern von Daten beim Aufrufen der View
        def get_object(self):
        # Call the superclass
        object = super(AuthorDetailView, self).get_object()
        # Record the last accessed date
        object.last_accessed = timezone.now()
        object.save()
        # Return the object
        return object
    '''

cv/templates/employee/detail.html
{% extends "base.html" %}

{% block content %}

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><a href="{% url 'employee:index' %}">Employees</a></li>
  <li class="active">{{ employee }}</li>
</ol>

<h1>{{ employee }}</h1>

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Personal information
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        First name: {{ employee.first_name }}<br/>
        Last name: {{ employee.last_name }}<br/>
        Position: {{ employee.get_position_display }}<br/>
        Place of birth: {{ employee.place_of_birth }}<br/>
        Year of birth: {{ employee.year_of_birth }}<br/>
        Citizenship: {{ employee.citizenship }}<br/>
        Familiy status: {{ employee.familiy_status }}<br/>
        Short description:<br/>
        <textarea class="form-control" rows="4">{{ employee.short_description }}</textarea>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          Skills
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        <h2>SAP modules</h2>
        {% for skill in employee.skill_set.all %}
    		<li class="list-group-item">{{ skill.sap_module }}</li>
		{% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

cv/templates/employee/employee_update_form.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>

cv/templates/employee/index.html
{% extends "base.html" %}

{% block content %}

<ol class="breadcrumb">
	<li><a href="/">Home</a></li>
	<li class="active">Employees</li>
</ol>

{% if employee_list %}
<table class="table table-striped">
   	<thead>
   		<tr>
   			<th>#</th>
   			<th>First name</th>
   			<th>Last name</th>
   			<th>Position</th>
   			<th>Detail</th>
   			<th>Edit</th>
   			<th>Action</th>
   		</tr>
   	<tbody>
   		{% for employee in employee_list %}
   		<tr>
   			<td>{{ employee.id }}</td>
   			<td>{{ employee.first_name }}</td>
   			<td>{{ employee.last_name }}</td>
   			<td>{{ employee.get_position_display }}</td>
   			<td><a href="{% url 'employee:detail' employee.id %}"><span class="glyphicon glyphicon-search"></span></a></td>
   			<td><a href="{% url 'employee:update' employee.id %}"><span class="glyphicon glyphicon-edit"></span></a></td>
   			<td><a href="{% url 'generator:create' employee.id %}"><span class="glyphicon glyphicon-cog"></span></a></td>
   		</tr>
   		{% endfor %}
   	</tbody>
</table>
{% else %}
<div class="alert alert-danger">No employees are available.</div>
{% endif %}

{% endblock %}